module01:
  testStringKey: testValue
  testBooleanKey: 0
  testIntKey: 10
  testFloatKey: 3.45
  testDoubleKey: 4.566
  testLongKey: 3234242

#以下配置为动态注入，通过setting.xml或者pom.xml文件的profile配置
global:
  homepage.medicareplans: '${homepage.medicareplans}'
  github.url: '${agent.images.host}'

local:
  profile.path: '${local.profile.path}'

ftp: '${ftp}'
#激活的环境配置
spring:
  profiles:
    active: '${spring.profiles.active}'
#端口
server:
  port: '${server.port}'

api:
  #Open to public network, could not call these api directly, call them via 3scale
  hmac:
    - xhf/create
    - xhf/update
    - xhfs
    - xhf/get-xhf
    - xhf/update-xhf-by-token
    - xhf/get-xhf-by-token
    - xhf/generate-token
    - xhf/validate-token
    - xhf/expire-token
    - xhf/completed-email
    - xhf/ping
    - xhf/re-send-odc-invitation
    - xhf/get-agent-notes
    - xhf/update-agent-notes
    - xhf/create-xhf-token

myProps: #自定义的属性和值
  simpleProp: simplePropValue
  arrayProps: 1,2,3,4,5
  listProp1:
    - name: Solin
      value: SolinValue
    - name: Tom
      value: TomValue
  listProp2:
    - config1Value1
    - config2Value2
  mapProps:
    key1: value1
    key2: value2